#Q08 Faça um programa que leia 5 números e informe a soma e a média dos números.

num1 = float ( input ( "Digite o 1º numero: " ))
num2 = float ( input ( "Digite o 2º numero: " ))
num3 = float ( input ( "Digite o 3º numero: " ))
num4 = float ( input ( "Digite o 4º numero: " ))
num5 = float ( input ( "Digite o 5º numero: " ))
soma = num1 + num2 + num3 + num4 + num5
print ( "A soma de todos os números -->" , soma ,)
print ( "A média 41458-->" , soma / 5 )
